# Generated by Django 3.2.19 on 2023-05-24 17:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='v1684659602/media/profile_img/default_kpyvr1', max_length=255, verbose_name='image'),
        ),
    ]
